openapi: 3.0.3
info:
  title: FinTracker
  description: Документация по работе с api-методами приложения FinTracker
  version: 1.0.0
  contact: {}
servers:
  - url: http://127.0.0.1:8080
tags:
  - name: fintracker
    description: Методы работы с таблицей учета расходов и доходов `spending`
paths:
  /fintracker/{id}:
    $ref: paths/fintracker_{id}.yaml
  /fintracker:
    $ref: paths/fintracker.yaml
components: {}
